# CONFIGURACIÓN DEL SISTEMA DE CONSTRUCCIÓN DEL PROYECTO
[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

# ACERCA DEL PROYECTO
[project]
name = "gestor_pacientes"
version = "0.1.0"
description = "Sistema de gestión de pacientes de un hospital"
authors = [{ name = "Claudia Fernández Ruiz", email = "cfr1012@alu.ubu.es" }]
requires-python = ">=3.10"
readme = "README.md"

# CONFIGURACIÓN DEL CÓDIGO FUENTE
[tool.setuptools]
package-dir = {"" = "src"}
[tool.setuptools.packages.find]
where = ["src"]